FORMAT: 1A

# Instela API
Instela API makes accessible *almost* every method used in Instela.

### Authentication

All the read-only endpoints can be accessed without authentication. But to make modification on the resources, an OAuth 2.0 access token should be provided.

### Return codes

All the methods returns appropiate HTTP return codes according to the result. Please check generic HTTP Status Codes at: https://github.com/thehivecluster/instela-api/blob/master/status-codes.md

# Group Entries
By **Entries API** you can access entries individually or by title.

# Gist Fox API Root [/]
Gist Fox API entry point.

## Entries Collection [/entries{?t}{?page}{?mode}{?order}]
### List all entries [GET]

+ Parameters
    + t (string,`wondrous`) ... Title
    + page (string, optional, `1`) ... Page
    + mode (string, optional, `today`) ... Visualization mode
             
            + Values
                  + `today` 
                  + `yesterday` 
                  + `only_friends` 
                  
    + order (string, optional, `today`) ... Order mode
            + Values
                  + `newest` 
                  + `best`
    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
